### ISSUE TITLE
안드로이드 앱 강제종료 문제

### ISSUE THREAD

**Issue by sukso96100** [s-owl/skhu-app#118]
0.3.0 압데이트 이후 안드로이드 기기 한정 앱 강제종료 이슈 있음.

```
FATAL EXCEPTION: ControllerMessenger
Process: com.sowl.skhus, PID: 10312
java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.react.bridge.NativeModule com.facebook.react.bridge.ReactContext.getNativeModule(java.lang.Class)' on a null object reference
    at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:320)
    at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:26)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at androidx.test.espresso.base.Interrogator.a(Interrogator.java:19)
    at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:166)
    at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:158)
    at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:34)
    at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:77)
    at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:52)
    at androidx.test.espresso.action.Tap.c(Tap.java:8)
    at androidx.test.espresso.action.Tap.b(Tap.java:18)
    at androidx.test.espresso.action.Tap$1.a(Tap.java:3)
    at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:20)
    at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
    at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:79)
    at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:96)
    at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6523)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.facebook.react.bridge.NativeModule com.facebook.react.bridge.ReactContext.getNativeModule(java.lang.Class)' on a null object reference
    at versioned.host.exp.exponent.modules.api.components.gesturehandler.react.RNGestureHandlerRootHelper.<init>(RNGestureHandlerRootHelper.java:48)
    at versioned.host.exp.exponent.modules.api.components.gesturehandler.react.RNGestureHandlerEnabledRootView.initialize(RNGestureHandlerEnabledRootView.java:49)
    at versioned.host.exp.exponent.modules.api.components.gesturehandler.react.RNGestureHandlerModule$2.execute(RNGestureHandlerModule.java:603)
    at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:583)
    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:917)
    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1025)
    at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:46)
    at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:983)
    at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:24)
    ... 24 more
```

**Comment by sukso96100** [comment]
#124 에 의해 해결된 것으로 보임. 유사 증상 발견시 추후 본 이슈 다시 열것.
